### ISSUE TITLE
Не добавляется в автозагрузку.

### ISSUE THREAD

**Issue by AAAlexyz** [alexazz19/SimpleSwitcher#1]
Не добавляется в автозагрузку.
Как добавить вручную, чтоб программа запускалась в фоне?

**Comment by pult** [comment]
Для ярлыка: SimpleSwitcher.exe /autostart
Должна создаться задача в шедулере. Возможно на старых виндах с этим что не так...

**Comment by alexazz19** [comment]
Попробуйте включить режим отладки (Настройки->Режим отладки) и снова попытаться добавить в автозагрузку. Рядом с exe файлом должен появиться файл логов с возможными ошибками. 

Про шедулер не совсем верно. Шедулерная задача создается только если пользователь хочет работать в режиме админа, так как только через шедулер можно запустить программу от администратора при старте windows. Если режим админа не требуется, до будет добавлена запись в реестре.

**Comment by alexazz19** [comment]
fixed in 1.0.3.0
