### ISSUE TITLE
Неверно обрабатывает комбинации

### ISSUE THREAD

**Issue by pult** [alexazz19/SimpleSwitcher#3]
Неверно обрабатывает комбинации - т.е. может обработать незавершённый шорткат.
Например для комбинации "Ctrl+Shift" будут обработаны все другие, типа  "Ctrl+Shift+1".
Похоже обрабатывается KEY_DOWN , а не KEY_UP. Это сильно влияет на все другие комбинации в других программах...

**Comment by alexazz19** [comment]
Да, все верно, обрабатывается KEY_DOWN. Это специально сделано для ускорение смены раскладки, чтобы она сменялась мгновенно (не ждать пока клавиша будет отпущена).
В принципе, описанную проблему можно решить, введя дополнительную настройку для каждой горячей клавиши - обрабатывать ее на key_down или key_up. Это не сложно реализовать.

**Comment by alexazz19** [comment]
Добавлена возможность срабатывания горячей клавиши на KEYUP вместо KEYDOWN
version 1.0.5.0
